# Generated by Django 6.1.1 on 2026-09-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID компании')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('website', models.TextField(verbose_name='Сайт')),
                ('vacancies', models.IntegerField(verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID вакансии')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата (от)')),
                ('area', models.CharField(max_length=50, verbose_name='Регион')),
                ('type', models.CharField(max_length=50, verbose_name='Тип занятости')),
                ('website', models.TextField(verbose_name='Ссылка на вакансию')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='company_vacancies', to='hh_parser.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancies',
                'ordering': ['-published_at'],
            },
        ),
    ]
